
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.5.1+f6fdcf537 for .NET Framework
      Сборка начата 12.06.2025 11:54:14.
      Included response file: C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\MSBuild\\Current\\Bin\\amd64\\MSBuild.rsp
      
      Проект "E:\\g++\\jarvis_voice\\vosk-api-master\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> E:\\g++\\jarvis_voice\\vosk-api-master\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Сборка проекта "E:\\g++\\jarvis_voice\\vosk-api-master\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:00.65
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        E:/g++/jarvis_voice/vosk-api-master/CMakeFiles/3.26.3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.5.1+f6fdcf537 for .NET Framework
      Сборка начата 12.06.2025 11:54:15.
      Included response file: C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\MSBuild\\Current\\Bin\\amd64\\MSBuild.rsp
      
      Проект "E:\\g++\\jarvis_voice\\vosk-api-master\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> E:\\g++\\jarvis_voice\\vosk-api-master\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Сборка проекта "E:\\g++\\jarvis_voice\\vosk-api-master\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:00.49
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        E:/g++/jarvis_voice/vosk-api-master/CMakeFiles/3.26.3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "E:/g++/jarvis_voice/vosk-api-master/CMakeFiles/CMakeScratch/TryCompile-p3qnuz"
      binary: "E:/g++/jarvis_voice/vosk-api-master/CMakeFiles/CMakeScratch/TryCompile-p3qnuz"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: E:/g++/jarvis_voice/vosk-api-master/CMakeFiles/CMakeScratch/TryCompile-p3qnuz
        
        Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_c2ebc.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.5.1+f6fdcf537 for .NET Framework
        Сборка начата 12.06.2025 11:54:16.
        Included response file: C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\MSBuild\\Current\\Bin\\amd64\\MSBuild.rsp
        
        Проект "E:\\g++\\jarvis_voice\\vosk-api-master\\CMakeFiles\\CMakeScratch\\TryCompile-p3qnuz\\cmTC_c2ebc.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_c2ebc.dir\\Debug\\".
          Создание каталога "E:\\g++\\jarvis_voice\\vosk-api-master\\CMakeFiles\\CMakeScratch\\TryCompile-p3qnuz\\Debug\\".
          Создание каталога "cmTC_c2ebc.dir\\Debug\\cmTC_c2ebc.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_c2ebc.dir\\Debug\\cmTC_c2ebc.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_c2ebc.dir\\Debug\\\\" /Fd"cmTC_c2ebc.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.35.32216.1 для x64
          CMakeCCompilerABI.c
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_c2ebc.dir\\Debug\\\\" /Fd"cmTC_c2ebc.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\g++\\jarvis_voice\\vosk-api-master\\CMakeFiles\\CMakeScratch\\TryCompile-p3qnuz\\Debug\\cmTC_c2ebc.exe" /INCREMENTAL /ILK:"cmTC_c2ebc.dir\\Debug\\cmTC_c2ebc.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/g++/jarvis_voice/vosk-api-master/CMakeFiles/CMakeScratch/TryCompile-p3qnuz/Debug/cmTC_c2ebc.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/g++/jarvis_voice/vosk-api-master/CMakeFiles/CMakeScratch/TryCompile-p3qnuz/Debug/cmTC_c2ebc.lib" /MACHINE:X64  /machine:x64 cmTC_c2ebc.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_c2ebc.vcxproj -> E:\\g++\\jarvis_voice\\vosk-api-master\\CMakeFiles\\CMakeScratch\\TryCompile-p3qnuz\\Debug\\cmTC_c2ebc.exe
        FinalizeBuildStatus:
          Файл "cmTC_c2ebc.dir\\Debug\\cmTC_c2ebc.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_c2ebc.dir\\Debug\\cmTC_c2ebc.tlog\\cmTC_c2ebc.lastbuildstate".
        Сборка проекта "E:\\g++\\jarvis_voice\\vosk-api-master\\CMakeFiles\\CMakeScratch\\TryCompile-p3qnuz\\cmTC_c2ebc.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:00.46
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "E:/g++/jarvis_voice/vosk-api-master/CMakeFiles/CMakeScratch/TryCompile-fx0f9q"
      binary: "E:/g++/jarvis_voice/vosk-api-master/CMakeFiles/CMakeScratch/TryCompile-fx0f9q"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: E:/g++/jarvis_voice/vosk-api-master/CMakeFiles/CMakeScratch/TryCompile-fx0f9q
        
        Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_f0f8b.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.5.1+f6fdcf537 for .NET Framework
        Сборка начата 12.06.2025 11:54:17.
        Included response file: C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\MSBuild\\Current\\Bin\\amd64\\MSBuild.rsp
        
        Проект "E:\\g++\\jarvis_voice\\vosk-api-master\\CMakeFiles\\CMakeScratch\\TryCompile-fx0f9q\\cmTC_f0f8b.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_f0f8b.dir\\Debug\\".
          Создание каталога "E:\\g++\\jarvis_voice\\vosk-api-master\\CMakeFiles\\CMakeScratch\\TryCompile-fx0f9q\\Debug\\".
          Создание каталога "cmTC_f0f8b.dir\\Debug\\cmTC_f0f8b.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_f0f8b.dir\\Debug\\cmTC_f0f8b.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_f0f8b.dir\\Debug\\\\" /Fd"cmTC_f0f8b.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.35.32216.1 для x64
          CMakeCXXCompilerABI.cpp
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_f0f8b.dir\\Debug\\\\" /Fd"cmTC_f0f8b.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\g++\\jarvis_voice\\vosk-api-master\\CMakeFiles\\CMakeScratch\\TryCompile-fx0f9q\\Debug\\cmTC_f0f8b.exe" /INCREMENTAL /ILK:"cmTC_f0f8b.dir\\Debug\\cmTC_f0f8b.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/g++/jarvis_voice/vosk-api-master/CMakeFiles/CMakeScratch/TryCompile-fx0f9q/Debug/cmTC_f0f8b.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/g++/jarvis_voice/vosk-api-master/CMakeFiles/CMakeScratch/TryCompile-fx0f9q/Debug/cmTC_f0f8b.lib" /MACHINE:X64  /machine:x64 cmTC_f0f8b.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_f0f8b.vcxproj -> E:\\g++\\jarvis_voice\\vosk-api-master\\CMakeFiles\\CMakeScratch\\TryCompile-fx0f9q\\Debug\\cmTC_f0f8b.exe
        FinalizeBuildStatus:
          Файл "cmTC_f0f8b.dir\\Debug\\cmTC_f0f8b.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_f0f8b.dir\\Debug\\cmTC_f0f8b.tlog\\cmTC_f0f8b.lastbuildstate".
        Сборка проекта "E:\\g++\\jarvis_voice\\vosk-api-master\\CMakeFiles\\CMakeScratch\\TryCompile-fx0f9q\\cmTC_f0f8b.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:00.49
        
      exitCode: 0
...
